export default {
  ADD_EXPENSE: 'ADD_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  SET_TEXT_FILTER: 'SET_TEXT_FILTER',
  SET_START_DATE: 'SET_START_DATE',
  SET_END_DATE: 'SET_END_DATE',
  SORT_BY_DATE: 'SORT_BY_DATE',
  SORT_BY_AMOUNT: 'SORT_BY_AMOUNT',
  SET_EXPENSES: 'SET_EXPENSES',
  START_EDIT_EXPENSE: 'START_EDIT_EXPENSE',
  START_REMOVE_EXPENSE: 'START_REMOVE_EXPENSE',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN'
};
